package main

import (
	"errors"
	"path"
	"strconv"

	"github.com/dofusdude/ankabuffer"
)

func DownloadItems(hashJson *ankabuffer.Manifest, bin int, version int, dir string, indent string, headless bool) error {
	outPath := dir
	outputPath := path.Join(dir, "output")

	if version == 3 {
		err := PullImages([]string{"stelzo/doduda-umbu:" + ARCH}, false, headless)
		if err != nil { return err }

		fileNames := []HashFile{
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_abusereasonsroot.asset.bundle", FriendlyName: "abusereasons.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_achievementcategoriesroot.asset.bundle", FriendlyName: "achievementcategories.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_achievementobjectivesroot.asset.bundle", FriendlyName: "achievementobjectives.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_achievementprogressroot.asset.bundle", FriendlyName: "achievementprogress.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_achievementprogressstepsroot.asset.bundle", FriendlyName: "achievementprogresssteps.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_achievementrewardsroot.asset.bundle", FriendlyName: "achievementrewards.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_achievementsroot.asset.bundle", FriendlyName: "achievements.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_actionfiltersroot.asset.bundle", FriendlyName: "actionfilters.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_activitysuggestionscategoriesroot.asset.bundle", FriendlyName: "activitysuggestionscategories.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_activitysuggestionsroot.asset.bundle", FriendlyName: "activitysuggestions.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_alignmentgiftroot.asset.bundle", FriendlyName: "alignmentgift.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_alignmentorderroot.asset.bundle", FriendlyName: "alignmentorder.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_alignmentrankjntgiftroot.asset.bundle", FriendlyName: "alignmentrankjntgift.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_alignmentrankroot.asset.bundle", FriendlyName: "alignmentrank.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_alignmentsidesroot.asset.bundle", FriendlyName: "alignmentsides.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_alignmenttitlesroot.asset.bundle", FriendlyName: "alignmenttitles.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_allianceranknamesuggestionsroot.asset.bundle", FriendlyName: "allianceranknamesuggestions.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_allianceranksroot.asset.bundle", FriendlyName: "allianceranks.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_alliancerightgroupsroot.asset.bundle", FriendlyName: "alliancerightgroups.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_alliancerightsroot.asset.bundle", FriendlyName: "alliancerights.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_alliancetagsroot.asset.bundle", FriendlyName: "alliancetags.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_alliancetagstypesroot.asset.bundle", FriendlyName: "alliancetagstypes.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_almanaxcalendarsroot.asset.bundle", FriendlyName: "almanaxcalendars.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_alterationcategoriesroot.asset.bundle", FriendlyName: "alterationcategories.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_alterationsroot.asset.bundle", FriendlyName: "alterations.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_appearancesroot.asset.bundle", FriendlyName: "appearances.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_areasroot.asset.bundle", FriendlyName: "areas.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_arenaleaguerewardsroot.asset.bundle", FriendlyName: "arenaleaguerewards.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_arenaleagueseasonsroot.asset.bundle", FriendlyName: "arenaleagueseasons.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_arenaleaguesroot.asset.bundle", FriendlyName: "arenaleagues.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_bonusescriterionsroot.asset.bundle", FriendlyName: "bonusescriterions.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_bonusesroot.asset.bundle", FriendlyName: "bonuses.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_breachbossesroot.asset.bundle", FriendlyName: "breachbosses.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_breachdungeonmodificatorsroot.asset.bundle", FriendlyName: "breachdungeonmodificators.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_breachinfinitylevelsroot.asset.bundle", FriendlyName: "breachinfinitylevels.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_breachprizesroot.asset.bundle", FriendlyName: "breachprizes.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_breachworldmapcoordinatesroot.asset.bundle", FriendlyName: "breachworldmapcoordinates.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_breachworldmapsectorsroot.asset.bundle", FriendlyName: "breachworldmapsectors.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_breedrolesroot.asset.bundle", FriendlyName: "breedroles.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_breedsroot.asset.bundle", FriendlyName: "breeds.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_censoredcontentsroot.asset.bundle", FriendlyName: "censoredcontents.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_censoredwordsroot.asset.bundle", FriendlyName: "censoredwords.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_challengesroot.asset.bundle", FriendlyName: "challenges.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_characteristiccategoriesroot.asset.bundle", FriendlyName: "characteristiccategories.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_characteristicsroot.asset.bundle", FriendlyName: "characteristics.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_characterxpmappingsroot.asset.bundle", FriendlyName: "characterxpmappings.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_chatchannelsroot.asset.bundle", FriendlyName: "chatchannels.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_choicesroot.asset.bundle", FriendlyName: "choices.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_collectablesroot.asset.bundle", FriendlyName: "collectables.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_collectionsroot.asset.bundle", FriendlyName: "collections.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_companioncharacteristicsroot.asset.bundle", FriendlyName: "companioncharacteristics.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_companionspellsroot.asset.bundle", FriendlyName: "companionspells.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_companionsroot.asset.bundle", FriendlyName: "companions.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_creaturebonesoverridesroot.asset.bundle", FriendlyName: "creaturebonesoverrides.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_creaturebonestypesroot.asset.bundle", FriendlyName: "creaturebonestypes.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_custommodebreedspellsroot.asset.bundle", FriendlyName: "custommodebreedspells.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_documentsroot.asset.bundle", FriendlyName: "documents.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_dungeonsroot.asset.bundle", FriendlyName: "dungeons.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_effectsroot.asset.bundle", FriendlyName: "effects.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_emblembackgroundsroot.asset.bundle", FriendlyName: "emblembackgrounds.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_emblemsymbolcategoriesroot.asset.bundle", FriendlyName: "emblemsymbolcategories.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_emblemsymbolsroot.asset.bundle", FriendlyName: "emblemsymbols.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_emoticonsroot.asset.bundle", FriendlyName: "emoticons.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_evolutiveeffectsroot.asset.bundle", FriendlyName: "evolutiveeffects.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_evolutiveitemtypesroot.asset.bundle", FriendlyName: "evolutiveitemtypes.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_expeditionseasonsroot.asset.bundle", FriendlyName: "expeditionseasons.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_externalnotificationsroot.asset.bundle", FriendlyName: "externalnotifications.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_featuredescriptionsroot.asset.bundle", FriendlyName: "featuredescriptions.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_fightscenariosroot.asset.bundle", FriendlyName: "fightscenarios.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_finishmovesroot.asset.bundle", FriendlyName: "finishmoves.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_forgettablespellsroot.asset.bundle", FriendlyName: "forgettablespells.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_guildchesttabsroot.asset.bundle", FriendlyName: "guildchesttabs.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_guildranknamesuggestionsroot.asset.bundle", FriendlyName: "guildranknamesuggestions.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_guildranksroot.asset.bundle", FriendlyName: "guildranks.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_guildrightgroupsroot.asset.bundle", FriendlyName: "guildrightgroups.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_guildrightsroot.asset.bundle", FriendlyName: "guildrights.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_guildtagsroot.asset.bundle", FriendlyName: "guildtags.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_guildtagstypesroot.asset.bundle", FriendlyName: "guildtagstypes.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_havenbagfurnituresroot.asset.bundle", FriendlyName: "havenbagfurnitures.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_havenbagthemesroot.asset.bundle", FriendlyName: "havenbagthemes.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_headsroot.asset.bundle", FriendlyName: "heads.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_hintcategoryroot.asset.bundle", FriendlyName: "hintcategory.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_hintsroot.asset.bundle", FriendlyName: "hints.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_housesroot.asset.bundle", FriendlyName: "houses.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_incarnationlevelsroot.asset.bundle", FriendlyName: "incarnationlevels.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_incarnationroot.asset.bundle", FriendlyName: "incarnation.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_infomessagesroot.asset.bundle", FriendlyName: "infomessages.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_interactivesroot.asset.bundle", FriendlyName: "interactives.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_itemsetsroot.asset.bundle", FriendlyName: "itemsets.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_itemsroot.asset.bundle", FriendlyName: "items.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_itemsupertypesroot.asset.bundle", FriendlyName: "itemsupertypes.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_itemtypesroot.asset.bundle", FriendlyName: "itemtypes.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_jobsroot.asset.bundle", FriendlyName: "jobs.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_kothrolesroot.asset.bundle", FriendlyName: "kothroles.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_legendarypowerscategoriesroot.asset.bundle", FriendlyName: "legendarypowerscategories.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_legendarytreasurehuntsroot.asset.bundle", FriendlyName: "legendarytreasurehunts.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_livingobjectskinjntmoodroot.asset.bundle", FriendlyName: "livingobjectskinjntmood.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_luaformulasroot.asset.bundle", FriendlyName: "luaformulas.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_mapcoordinatesroot.asset.bundle", FriendlyName: "mapcoordinates.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_mappositionsroot.asset.bundle", FriendlyName: "mappositions.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_mapreferencesroot.asset.bundle", FriendlyName: "mapreferences.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_mapscrollactionsroot.asset.bundle", FriendlyName: "mapscrollactions.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_modstersroot.asset.bundle", FriendlyName: "modsters.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_monsterminibossroot.asset.bundle", FriendlyName: "monsterminiboss.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_monsterracesroot.asset.bundle", FriendlyName: "monsterraces.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_monstersroot.asset.bundle", FriendlyName: "monsters.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_monstersuperracesroot.asset.bundle", FriendlyName: "monstersuperraces.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_monthsroot.asset.bundle", FriendlyName: "months.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_mountbehaviorsroot.asset.bundle", FriendlyName: "mountbehaviors.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_mountbonesroot.asset.bundle", FriendlyName: "mountbones.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_mountfamilyroot.asset.bundle", FriendlyName: "mountfamily.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_mountsroot.asset.bundle", FriendlyName: "mounts.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_namingrulesroot.asset.bundle", FriendlyName: "namingrules.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_notificationsroot.asset.bundle", FriendlyName: "notifications.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_npcactionsroot.asset.bundle", FriendlyName: "npcactions.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_npcmessagesroot.asset.bundle", FriendlyName: "npcmessages.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_npcsroot.asset.bundle", FriendlyName: "npcs.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_optionalfeaturesroot.asset.bundle", FriendlyName: "optionalfeatures.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_ornamentsroot.asset.bundle", FriendlyName: "ornaments.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_packroot.asset.bundle", FriendlyName: "pack.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_playlistsroot.asset.bundle", FriendlyName: "playlists.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_pointofinterestcategoryroot.asset.bundle", FriendlyName: "pointofinterestcategory.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_pointofinterestroot.asset.bundle", FriendlyName: "pointofinterest.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_popupinformationsroot.asset.bundle", FriendlyName: "popupinformations.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_preseticonsroot.asset.bundle", FriendlyName: "preseticons.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_questcategoryroot.asset.bundle", FriendlyName: "questcategory.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_questobjectivesroot.asset.bundle", FriendlyName: "questobjectives.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_questobjectivetypesroot.asset.bundle", FriendlyName: "questobjectivetypes.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_questsroot.asset.bundle", FriendlyName: "quests.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_queststeprewardsroot.asset.bundle", FriendlyName: "queststeprewards.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_queststepsroot.asset.bundle", FriendlyName: "queststeps.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_randomdropgroupsroot.asset.bundle", FriendlyName: "randomdropgroups.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_recipesroot.asset.bundle", FriendlyName: "recipes.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_ridefoodroot.asset.bundle", FriendlyName: "ridefood.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_servercommunitiesroot.asset.bundle", FriendlyName: "servercommunities.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_servergametypesroot.asset.bundle", FriendlyName: "servergametypes.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_serverlangsroot.asset.bundle", FriendlyName: "serverlangs.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_serverpopulationsroot.asset.bundle", FriendlyName: "serverpopulations.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_serverseasonsroot.asset.bundle", FriendlyName: "serverseasons.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_serversroot.asset.bundle", FriendlyName: "servers.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_signsroot.asset.bundle", FriendlyName: "signs.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_skillnamesroot.asset.bundle", FriendlyName: "skillnames.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_skillsroot.asset.bundle", FriendlyName: "skills.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_skinmappingsroot.asset.bundle", FriendlyName: "skinmappings.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_skinslotsrulesroot.asset.bundle", FriendlyName: "skinslotsrules.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_smileycategoriesroot.asset.bundle", FriendlyName: "smileycategories.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_smileypacksroot.asset.bundle", FriendlyName: "smileypacks.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_smileysroot.asset.bundle", FriendlyName: "smileys.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_soundbonesroot.asset.bundle", FriendlyName: "soundbones.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_sounduihookroot.asset.bundle", FriendlyName: "sounduihook.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_sounduiroot.asset.bundle", FriendlyName: "soundui.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_speakingitemstextroot.asset.bundle", FriendlyName: "speakingitemstext.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_speakingitemstriggersroot.asset.bundle", FriendlyName: "speakingitemstriggers.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_spellbombsroot.asset.bundle", FriendlyName: "spellbombs.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_spellconversionsroot.asset.bundle", FriendlyName: "spellconversions.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_spelllevelsroot.asset.bundle", FriendlyName: "spelllevels.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_spellpairsroot.asset.bundle", FriendlyName: "spellpairs.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_spellscriptsroot.asset.bundle", FriendlyName: "spellscripts.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_spellsroot.asset.bundle", FriendlyName: "spells.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_spellstatesroot.asset.bundle", FriendlyName: "spellstates.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_spelltypesroot.asset.bundle", FriendlyName: "spelltypes.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_spellvariantsroot.asset.bundle", FriendlyName: "spellvariants.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_stealthbonesroot.asset.bundle", FriendlyName: "stealthbones.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_subareasroot.asset.bundle", FriendlyName: "subareas.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_subhintsroot.asset.bundle", FriendlyName: "subhints.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_superareasroot.asset.bundle", FriendlyName: "superareas.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_taxcollectorfirstnamesroot.asset.bundle", FriendlyName: "taxcollectorfirstnames.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_taxcollectornamesroot.asset.bundle", FriendlyName: "taxcollectornames.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_texticonreferencesroot.asset.bundle", FriendlyName: "texticonreferences.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_tipsroot.asset.bundle", FriendlyName: "tips.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_titlecategoriesroot.asset.bundle", FriendlyName: "titlecategories.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_titlesroot.asset.bundle", FriendlyName: "titles.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_veteranrewardsroot.asset.bundle", FriendlyName: "veteranrewards.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_waypointsroot.asset.bundle", FriendlyName: "waypoints.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_worldeventsroot.asset.bundle", FriendlyName: "worldevents.asset.bundle" },
			{ Filename: "Dofus_Data/StreamingAssets/Content/Data/data_assets_worldmapsroot.asset.bundle", FriendlyName: "worldmaps.asset.bundle" },
		}

		err = DownloadUnpackFiles("Unpacking data", bin, hashJson, "data", fileNames, dir, outputPath, true, indent, headless, false)
		if err != nil { return err }

		return err
	} else if version == 2 {
		fileNames := []HashFile{
			{Filename: "data/common/Items.d2o", FriendlyName: "items.d2o"},
			{Filename: "data/common/ItemTypes.d2o", FriendlyName: "item_types.d2o"},
			{Filename: "data/common/ItemSets.d2o", FriendlyName: "item_sets.d2o"},
			{Filename: "data/common/Effects.d2o", FriendlyName: "effects.d2o"},
			{Filename: "data/common/Bonuses.d2o", FriendlyName: "bonuses.d2o"},
			{Filename: "data/common/Recipes.d2o", FriendlyName: "recipes.d2o"},
			{Filename: "data/common/Spells.d2o", FriendlyName: "spells.d2o"},
			{Filename: "data/common/SpellTypes.d2o", FriendlyName: "spell_types.d2o"},
			{Filename: "data/common/Breeds.d2o", FriendlyName: "breeds.d2o"},
			{Filename: "data/common/Mounts.d2o", FriendlyName: "mounts.d2o"},
			{Filename: "data/common/Idols.d2o", FriendlyName: "idols.d2o"},
			{Filename: "data/common/MonsterRaces.d2o", FriendlyName: "monster_races.d2o"},
			{Filename: "data/common/Monsters.d2o", FriendlyName: "monsters.d2o"},
			{Filename: "data/common/CompanionCharacteristics.d2o", FriendlyName: "companion_chars.d2o"},
			{Filename: "data/common/CompanionSpells.d2o", FriendlyName: "companion_spells.d2o"},
			{Filename: "data/common/Companions.d2o", FriendlyName: "companions.d2o"},
			{Filename: "data/common/Areas.d2o", FriendlyName: "areas.d2o"},
			{Filename: "data/common/MountFamily.d2o", FriendlyName: "mount_family.d2o"},
			{Filename: "data/common/Npcs.d2o", FriendlyName: "npcs.d2o"},
			{Filename: "data/common/ServerGameTypes.d2o", FriendlyName: "server_game_types.d2o"},
			{Filename: "data/common/CharacteristicCategories.d2o", FriendlyName: "chars_categories.d2o"},
			{Filename: "data/common/CreatureBonesTypes.d2o", FriendlyName: "creature_bone_types.d2o"},
			{Filename: "data/common/CreatureBonesOverrides.d2o", FriendlyName: "create_bone_overrides.d2o"},
			{Filename: "data/common/EvolutiveEffects.d2o", FriendlyName: "evol_effects.d2o"},
			{Filename: "data/common/BonusesCriterions.d2o", FriendlyName: "bonus_criterions.d2o"},
			{Filename: "data/common/Titles.d2o", FriendlyName: "titles.d2o"},
		}

		err := DownloadUnpackFiles("Items", bin, hashJson, "main", fileNames, dir, outPath, true, indent, headless, false)

		return err
	} else {
		return errors.New("unsupported version: " + strconv.Itoa(version))
	}
}