name: Persistence Update

on:
    workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v .

    - name: Run and Update
      run: |
        ./doduda --ignore mountsimages
        ./doduda parse --persistence-dir persistent
        git add persistent
        git commit -m "Update persistent"
        git push origin main
